-- Drop all tables with CASCADE
DROP TABLE IF EXISTS "UserRoles" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Roles" CASCADE;
DROP TABLE IF EXISTS "Registrations" CASCADE;
DROP TABLE IF EXISTS "Seasons" CASCADE;
DROP TABLE IF EXISTS "Companies" CASCADE;
DROP TABLE IF EXISTS "Locations" CASCADE;
DROP TABLE IF EXISTS "VehicleDetails" CASCADE;
DROP TABLE IF EXISTS "VehicleContracts" CASCADE;
DROP TABLE IF EXISTS "Vehicles" CASCADE;
DROP TABLE IF EXISTS "ServiceProviders" CASCADE;
DROP TABLE IF EXISTS "VehicleRoutes" CASCADE;
DROP TABLE IF EXISTS "AirlineRoutes" CASCADE;
DROP TABLE IF EXISTS "MealTypes" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;

-- Verify all tables are dropped
SELECT tablename FROM pg_tables WHERE schemaname = 'public';
